Feature/user dropdown
avkvirtru/virtuoso-design-system pull request #151
Opened 2021-03-25 20:00 UTC by korobko-virtru

Created user dropdown component which is used by multiple projects to show active user and logout button (available list of  users to  login wasn't implemented as discussed with Rob)

2021-03-31 21:36 UTC, avkvirtru requested changes
Good start! I did a visual review. Only minor change is to swap the arrows:

When the component dropdown is **collapsed** (default), the arrow should be pointing down.
<img width="251" alt="image" src="https://user-images.githubusercontent.com/44370126/113214326-28777380-922e-11eb-926f-3c5bec078b91.png">

And when it's **expanded**, the arrow should point up. It's currently the opposite.

<img width="369" alt="image" src="https://user-images.githubusercontent.com/44370126/113214491-6eccd280-922e-11eb-8072-fc74d0760f17.png">
 

Here's the original design: https://virtru.invisionapp.com/console/share/U91B8PCFD7/363845315

2021-03-31 21:37 UTC, avkvirtru commented
@jrschumacher could you code review this when you have a chance?

2021-04-02 14:54 UTC, korobko-virtru commented
> Good start! I did a visual review. Only minor change is to swap the arrows:
> 
> When the component dropdown is **collapsed** (default), the arrow should be pointing down.
> <img alt="image" width="251" src="https://user-images.githubusercontent.com/44370126/113214326-28777380-922e-11eb-926f-3c5bec078b91.png">
> 
> And when it's **expanded**, the arrow should point up. It's currently the opposite.
> 
> <img alt="image" width="369" src="https://user-images.githubusercontent.com/44370126/113214491-6eccd280-922e-11eb-8072-fc74d0760f17.png">
> 
> Here's the original design: https://virtru.invisionapp.com/console/share/U91B8PCFD7/363845315

Done

2021-04-02 16:24 UTC, avkvirtru approved these changes
LG2M, pending @jrschumacher code review :)

2021-07-12 17:47 UTC, avkvirtru commented
@jrschumacher did we want to pick up this neglected PR?

2025-05-07 11:48 UTC, dcrowley92 commented
This repository has been archived. Closing this PR automatically.

2025-05-07 11:48 UTC, closed without merging